; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
name = Eclipse-pH-Mainboard
description = "This project covers the primary code for the Eclipse-pH Mainboard."
default_envs = main

[env]
platform = nordicnrf52
framework = arduino
board = adafruit_feather_nrf52840
build_src_flags = -Werror -Wall -Wdouble-promotion -Wclobbered -Wempty-body -Wuninitialized
;build_src_filter = +<*.h> +<examples/${sysenv.PIOENV}.cpp>
lib_deps = 
	teemuatlut/TMCStepper @ ^0.7.3
	SPI
	Wire
	sparkfun/SparkFun MAX1704x Fuel Gauge Arduino Library@^1.0.4
	arduino-libraries/SD@^1.2.4
	adafruit/RTClib@^2.1.1
	adafruit/Adafruit BusIO@^1.14.5
	teemuatlut/TMCStepper@^0.7.3
;lib_archive = no
monitor_speed = 115200
check_tool = cppcheck, clangtidy
check_src_filters = +<src/*> +<test/*> +<lib/*> -<.pio/*>
check_flags = 
	clangtidy: --checks=bugprone-*,clang-analyzer-*,cppcoreguidelines-*,misc-*,performance-*,portability-*,readability-*,-cppcoreguidelines-macro-usage,-cppcoreguidelines-avoid-magic-numbers,-readability-magic-numbers
	cppcheck: --enable=all --addon=misra.json --suppress=*:*/.pio/* --suppress=*:*/home/runner/.platformio/packages/* --suppress=unmatchedSuppression --suppress=cstyleCast

[env:main]
build_src_filter = +<*.h> +<main.cpp>

; Example files
; To create a new example, create a new example file in the examples folder
; and add a new environment here with the same name as the file.
[env:adpd4101example]
build_src_filter = +<*.h> +<examples/adpd4101example.cpp>
[env:ltc2984example]
build_src_filter = +<*.h> +<examples/ltc2984example.cpp>
[env:benchtest]
build_src_filter = +<*.h> +<examples/benchtest.cpp>

